### PR TITLE
Mention PolyMC in the installation guide.

### PR DESCRIPTION
**Pull request by Sneedplex**
Mentions PolyMC in the installation guide to indicate compatibility.

### CODE REVIEW

**Review by UselessBullets — COMMENTED** [review]
Afaik we explicitly avoid mentioning polymc

**Comment by SkyDeckAGoGo** [comment]
Closing this because we don't officially support PolyMC and while it works currently, we can't guarantee that in the future. People who want to use PolyMC likely know how to set it up anyway since its the same process as Prism.

**Comment by Sneedplex** [comment]
> Closing this because we don't officially support PolyMC

You don't "support" a modloader. If you distribute everything in the standard modpack format then there are no issues. PolyMC has no plans to destroy backwards compatibility with MultiMC. This is a non-argument.

**Comment by UselessBullets** [comment]
We, do not currently test for or validate support for PolyMC and just because it doesn't "plan" to break backwards compatibility doesn't mean it doesn't *occasionally* do so. We guarantee support for MultiMC and Prism, we do not for PolyMC or other mc launchers.

**Comment by Sneedplex** [comment]
> We, do not currently test for or validate support for PolyMC and just because it doesn't "plan" to break backwards compatibility doesn't mean it doesn't _occasionally_ do so. We guarantee support for MultiMC and Prism, we do not for PolyMC or other mc launchers.

Solution: test it.

**Comment by UselessBullets** [comment]
nah

**Pull request closed without merging**
